name: Deploy Blog Site

on:
  push:
    branches:
      - master # 或者是您用于部署的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.11.1" # 指定 Node.js 版本

      - name: Install VitePress globally
        run: npm add -D vitepress

      - name: Install dependencies
        run: npm install

      - name: Build VitePress site
        run: npm run build # 构建站点的命令

      - name: Deploy to Aliyun Server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: ".vitepress/dist/*"
          REMOTE_HOST: ${{ secrets.DEPLOYMENT_IP }}
          REMOTE_USER: "root"
          TARGET: "/app/dist"